sonar.organization=matiaselima
sonar.projectKey=MatiasELima_ics-parcial2

# Esto le dice qué analizar y qué ignorar
sonar.sources=.
sonar.exclusions=node_modules/**, *.test.js, coverage/**, **/*.js
sonar.tests=.
sonar.test.inclusions=*.test.js

# Lenguaje del proyecto
sonar.javascript.lcov.reportPaths=coverage/lcov.info